### ISSUE TITLE
release a new version?

### ISSUE THREAD

**Issue by swanderz** [dbt-msft/tsql-utils#31]
The fix of release a version that doesn't have a 4th integer is easy, but hesitant to introduce yet another version set to match...
https://github.com/fishtown-analytics/dbt/issues/3109

**Comment by infused-kim** [comment]
The new version was released, but the README.md is not updated yet. It should be changed to:

```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.4
  - package: dbt-msft/tsql_utils
    version: 0.6.5
```
