### ISSUE TITLE
Multi-field surrogate key failing due to using default dbt_utils concat macro

### ISSUE THREAD

**Issue by chiblackhawks** [dbt-msft/tsql-utils#62]
Hi,

I noticed while using surrogate_key that the compiled sql was syntactically incorrect due to the operator used to concat the list of fields I am passing to the macro. After some triage, I realized that it was using the default dbt_utils.concat() macro which uses '||' to concat.

In order to resolve this, I added the following to my dbt_project.yml:

```
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['tsql_utils', 'dbt_utils']

vars:
  dbt_utils_dispatch_list: ['tsql_utils']
  dbt_date_dispatch_list: ['tsql_utils']
  audit_helper_dispatch_list: ['tsql_utils']
  dbt_expectations_dispatch_list: ['tsql_utils']

```

This solved the issue but I am not confident that this is the correct solution?
