### ISSUE TITLE
get_date_dimension not working

### ISSUE THREAD

**Issue by hammadhasandogar** [dbt-msft/tsql-utils#74]
Seems like compiled query generates nested CET expression, which causes the failure.

`{{ dbt_date.get_date_dimension('2000-01-01', '2050-12-31') }}`
`Incorrect syntax near 'with'.`

```
with base_dates as (    
with date_spine as (...
```

package.yml
```
packages:
  - package: calogica/dbt_date
    version: 0.4.1
  - package: dbt-labs/dbt_utils
    version: 0.7.4
  - package: dbt-msft/tsql_utils
    version: 0.8.1
```
dispatch defined in dbt_project.yml
```
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['tsql_utils', 'dbt_utils']
  - macro_namespace: dbt_date
    search_order: ['tsql_utils', 'dbt_date']
```
